# Generated by Django 3.2.9 on 2021-12-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=20)),
                ('reg_date', models.DateField()),
                ('inv_number', models.CharField(max_length=20)),
                ('subject', models.TextField()),
                ('note', models.TextField()),
                ('file', models.FileField(upload_to='agreements/')),
            ],
            options={
                'verbose_name': 'Соглашение',
                'verbose_name_plural': 'Соглашения',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Foiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('short', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'ФОИВ',
                'verbose_name_plural': 'ФОИВы',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_protocol', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тип протокол',
                'verbose_name_plural': 'Типы протоколов',
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=20)),
                ('reg_date', models.DateField()),
                ('inv_number', models.CharField(max_length=20)),
                ('from_mvd', models.TextField()),
                ('for_mvd', models.TextField()),
                ('note', models.TextField()),
                ('file', models.FileField(upload_to='protocol/')),
                ('agr_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agreements.agreements')),
                ('type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agreements.type')),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протоколы',
            },
        ),
        migrations.AddField(
            model_name='agreements',
            name='departments',
            field=models.ManyToManyField(to='agreements.Department', verbose_name='Уполномоченные подразделения'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='foiv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agreements.foiv'),
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=20)),
                ('reg_date', models.DateField()),
                ('inv_number', models.CharField(max_length=20)),
                ('subject', models.TextField()),
                ('note', models.TextField()),
                ('file', models.FileField(upload_to='additional/')),
                ('agr_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agreements.agreements')),
                ('departments', models.ManyToManyField(to='agreements.Department', verbose_name='Уполномоченные подразделения')),
            ],
            options={
                'verbose_name': 'Доп. соглашение',
                'verbose_name_plural': 'Доп. соглашения',
            },
        ),
    ]
