# Generated by Django 3.2.9 on 2021-12-27 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='agr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.agreements', verbose_name='Соглашение'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='departments',
            field=models.ManyToManyField(blank=True, to='agreements.Department', verbose_name='Уполномоченные подразделения'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='additional/', verbose_name='Доп.соглашение(PDF-формат)'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='inv_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='reg_date',
            field=models.DateField(verbose_name='Дата заключения доп.соглашения'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='Предмет доп.соглашения'),
        ),
        migrations.AlterField(
            model_name='additional',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название доп.соглашения'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='departments',
            field=models.ManyToManyField(blank=True, to='agreements.Department', verbose_name='Уполномоченные подразделения'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='agreements/', verbose_name='Соглашение(PDF-формат)'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='foiv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.foiv', verbose_name='ФОИВ'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='inv_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='reg_date',
            field=models.DateField(verbose_name='Дата заключения соглашения'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='Предмет соглашения'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название соглашения'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Ответственные подразделения'),
        ),
        migrations.AlterField(
            model_name='foiv',
            name='short',
            field=models.CharField(max_length=20, verbose_name='Краткое название ФОИВ'),
        ),
        migrations.AlterField(
            model_name='foiv',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Полное название ФОИВ'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='agr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.agreements', verbose_name='Соглашение'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='protocol/', verbose_name='Протокол (PDF-формат)'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='for_mvd',
            field=models.TextField(blank=True, null=True, verbose_name='Данные для МВД'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='from_mvd',
            field=models.TextField(blank=True, null=True, verbose_name='Данные от МВД'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='inv_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='reg_date',
            field=models.DateField(verbose_name='Дата регистрации протокола'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название протокола'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreements.type', verbose_name='Тип протокола'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_protocol',
            field=models.CharField(max_length=50, verbose_name='Тип протокола'),
        ),
    ]
